# Copyright (c) 2020-2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved. 
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction, 
# disclosure or distribution of this material and related documentation 
# without an express license agreement from NVIDIA CORPORATION or 
# its affiliates is strictly prohibited.

ARG BASE_IMAGE=neuralbody:latest
FROM $BASE_IMAGE

# additional libraries

# Fix install error https://github.com/scopatz/pyembree/issues/36
COPY requirements.txt /workspace/requirements.txt
RUN pip install -r requirements.txt && \
pip install imageio==2.4.0 && \
conda install -y -c conda-forge embree=2.17.7 && \
conda install -y -c conda-forge pyembree

# install nvdiffrast
RUN git config --global http.proxy http://10.81.45.119:9910 && pip install "git+https://github.com/facebookresearch/pytorch3d.git@v0.6.0"
# RUN git config --global http.proxy http://10.81.45.119:9910 && pip install git+https://github.com/NVlabs/nvdiffrast/

# HDR image support
# RUN http_proxy='socks://219.223.185.245:1080' https_proxy='socks://219.223.185.245:1080' imageio_download_bin freeimage
